### ISSUE TITLE
Do a release and move to beta status

### ISSUE THREAD

**Issue by almarklein** [flexxui/flexx#431]
With #408 merged, Flexx is in a good shape to move forward. We should do a release soon to make it easier for people to try it out. This will also mark the end of the alpha stage. Just a few things that I want to do first:

* [x] Put up a landing page at a nice domain: we are http://flexx.live
* [x] Spin up a new demo server ~~and the good old Raspberry pi~~
* [x] Decide and implement the spinning out of sub-packages #428
* [x] Make a start with better structuring the docs #414
* [x] Allow users to publish static apps to the web (#430)
* [ ] If not too much work, allow actions to be co-routines #413
* [x] Do something with #405 and #402
* [x] Improve default styling and write example to demonstrate basic "theming" (also see #139) via #445
* [x] Be more explicit about browser support #341
* [x] Now that users can deploy to the web and view on phone: mouse events on mobile devices #149 
* [x] #209 
* [x] Fix #293 (by #441)
* [x] More compelling examples (e.g. with D3, ThreeJS, plotly, dashboard-like, ...)
* [ ] Mechanism and example to open files. #485
* [x] Much better error reporting in JS ...
* [x] Document `Widget.node` and `Widget.outernode`.
* [x] Adding a `Widget.minsize` prop should overcome some quircks in VBox/VFix #465.

Note that there are more "leftover" tasks mentioned in #408, but these can be done in subsequent releases.

**Comment by almarklein** [comment]
Closing. All points have been addressed, except a few which I've marked for 0.6. I'm working on some docs and then its release time, I guess.
